### PR TITLE
Linux support, only supports google drive

### PR DESCRIPTION
**Pull request by vossim**
Simple linux support, only works with google drive at the moment.

For some reason I cannot get the plgx version to work, but this does work with the dll and dependencies copied into the Plugins directory.

### CODE REVIEW

**Comment by MilorES** [comment]
How can I download it? And install it?

**Comment by auwsom** [comment]
Hi, I found a KeeAnywhere.dll file in the zip release here (https://github.com/Kyrodan/KeeAnywhere/releases), It required an older version of KP 2.43 to run. And it runs without complaining errors on the NET requirements of the plugin (running with mono KeePass.exe) on Ubuntu. 

However, its not listed as a plugin and cant find how to sync.. any ideas? Thanks

**Comment by zgmnkv** [comment]
@Kyrodan any chances to merge this?

**Comment by PhoneixS** [comment]
I have compiled this version but it doesn't run correctly, it throws an exception when loading at the start of KeePass.

```
/usr/lib/keepass2/Plugins/KeeAnywhere/KeeAnywhere.dll

Exception has been thrown by the target of an invocation.
mscorlib
 at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x0001a] in <a17fa1457c5d44f2885ac746c1764ea5>:0
 at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00095] in <a17fa1457c5d44f2885ac746c1764ea5>:0
...

Inner:
The type initializer for 'KeeAnywhere.KeeAnyWhereExt' threw an exception.
 at (wrapper managed-to-native) System.Reflection.RuntimeConstructorInfo.InternalInvoke(System.Reflection.RuntimeConstructorInfo, object, object[], System.Exception&)
 at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, SystemBoolean wrapExceptions) [0x00005] in <a17fa1457c5d44f2885ac746c1764ea5>:0
```

**Comment by Kyrodan** [comment]
Hi @vossim,

we should close this without merge because v2.0.0 is nearly there and hopefully contains fixes for this PR.
Can you try the beta-builds from #252 and report back?

**Pull request closed without merging**
